### ISSUE TITLE
Generate data file

### ISSUE THREAD

**Issue by cpommier** [elixir-europe/plant-brapi-to-isa#14]

**Comment by cpommier** [comment]
Need to add in brapi_to_isa.py:
line 395
```
for my_study_id in STUDY_IDS:
    my_study = brapi_client.get_study(my_study_id)
    if "trialDbId" in my_study.keys() and my_study["trialDbId"]:
      TRIAL_IDS += my_study["trialDbId"]
    elif "trialDbIds" in my_study.keys() and my_study["trialDbIds"]:
       TRIAL_IDS += my_study["trialDbIds"]

```

**Comment by cpommier** [comment]
TODO:
- Move pull request toward that branch
- Test with CIRAD and iBET endpoints

**Comment by cpommier** [comment]
Germplasm : 
"observationUnitXref": [
{
"source": "gnpis.lot",
"id": "0040E"
}
"accessionNumber": "274Col49",
"germplasmName": "Riesling B INRA-CV 813",

Levels

**Comment by bedroesb** [comment]
> Germplasm :
> "observationUnitXref": [
> {
> "source": "gnpis.lot",
> "id": "0040E"
> }
> "accessionNumber": "274Col49",
> "germplasmName": "Riesling B INRA-CV 813",
> 
> Levels

can 
{
"source": "gnpis.lot",
"id": "0040E"
} 
be placed under a single column or separate it in  observationUnitXref[source], observationUnitXref[id] columns?

**Comment by cpommier** [comment]
Most of the time there will be a single source. In our case there are gnpis.lot and biosample, but only lot is filled.
