### ISSUE TITLE
Handle VIRTUAL_Trials level

### ISSUE THREAD

**Issue by cpommier** [elixir-europe/plant-brapi-to-isa#16]
With 

> -e https://urgi.versailles.inra.fr/gnpis-core-srv/brapi/v1/ -t24

The data files are not generated

**Comment by bedroesb** [comment]
Thanks, will be solved in next update

**Comment by bedroesb** [comment]
I should have refreshed the page, I was not aware of your commit.

**Comment by bedroesb** [comment]
@cpommier, can you revert the commit? I was going to add the season function + I have a fix that is not virtual trial specific, because I found out that I had the same problem with some of our studies as well.

**Comment by cpommier** [comment]
@bedroesb oups sorry. My modifications are minor so you should be able to pull them in your branch before merging.

**Comment by cpommier** [comment]
Ho, in fact you mean that you have a better fix. Hold on

**Comment by bedroesb** [comment]
I applied, already your renamings to mine, an improvement ;) actually the virtual trial problem was really small, I was not checking if there were obervation levelS available, expect a pull request within the hour :)

**Comment by cpommier** [comment]
Revert done, do you see it ?

**Comment by bedroesb** [comment]
yes, sorry for the confusion. I should have communicated I was working on it.

**Comment by cpommier** [comment]
Done
