### ISSUE TITLE
Handle seasons/phenotyping campains

### ISSUE THREAD

**Issue by cpommier** [elixir-europe/plant-brapi-to-isa#17]
In 
> -e https://urgi.versailles.inra.fr/gnpis-core-srv/brapi/v1/ -sRIGW1

The seasons are not added as a dedicated column and the data might be splited on several rows.

**Comment by bedroesb** [comment]
How would you represent seasons in the case you metioned?
I would like to stick with one collumn

```json
"seasons": [
      "2006",
      "2007",
      "2008",
      "2009"
    ]
```

**Comment by bedroesb** [comment]
I guess just a column with season is enough since the data file is on observation level, which is only one season. In this example 2007

```
{
            "observationDbId": "5260355",
            "observationVariableDbId": "CO_356:1000011",
            "observationVariableName": "FLO_50",
            "observationTimeStamp": null,
            "season": "2007",
            "collector": null,
            "value": "2007-05-24"
          }
```
