### ISSUE TITLE
Things that still need to be implemented/fixed

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/plant-brapi-to-isa#36]
Based on the isa configuration files and example isa-tab files generated by the brapi 2 isa script, following issues with the isa validator were detected:

## Warnings in the study file:

```json
"message": "Missing Protocol declaration",
            "supplemental": "Protocol(s) of type ['Growth'] defined in the ISA-configuration expected as a between 'Source Name' and 'Sample Name' but has not been found, in the file 's_VIB_study___55.txt'",
            "code": 1007
```

info:
```json
            "message": "Found -1 study groups in s_VIB_study___55.txt",
            "supplemental": "Found -1 study groups in s_VIB_study___55.txt",
            "code": 5001
```

## Warnings in the assay file:

```json
"message": "Missing Protocol declaration",
            "supplemental": "Protocol(s) of type ['Phenotyping', 'Sampling'] defined in the ISA-configuration expected as a between 'Sample Name' and 'Assay Name' but has not been found, in the file 'a_VIB_study___55_plant.txt'",
            "code": 1007
```

```json
"message": "Missing Protocol declaration",
            "supplemental": "Protocol(s) of type ['Data Transformation'] defined in the ISA-configuration expected as a between 'Assay Name' and 'Derived Data File' but has not been found, in the file 'a_VIB_study___55_plant.txt'",
            "code": 1007
```

## To be implemented:

Characteristics[Observation Unit Type] in assay file.

repo with isa validator:
https://github.com/bedroesb/isa-validation

**Comment by bedroesb** [comment]
info:
```json
            "message": "Found -1 study groups in s_VIB_study___55.txt",
            "supplemental": "Found -1 study groups in s_VIB_study___55.txt",
            "code": 5001
```

**Comment by bedroesb** [comment]
@proccaserra the Characteristics[Observation Unit Type] column in the assay file is actually the last thing that needs to be implemented before I call it good enough. I can implement it the dirty way and insert the column after the isa tab files are generated, but I would prefer an isa api way to have this column :)

**Comment by proccaserra** [comment]
@bedroesb but is this needed in the assay file if the assay type is defined by a 'technology type' such as the one currently implemented 

"BLOCK>PLOT level analysis"
"BLOCK>PLOT>PLANT level analysis"

I am not too keen on the use of ">" and upper case for 'block', 'plot' and 'plant'.
I have suggested a number of possible values, this is part of the discussion for MIAPPE and BRAPI but I have not seen this being discussed on the list or I have not been included in the discussion.
@cpommier do you know more about the feedback sent to BRAPI developers following all the work we did on the conversion to ISA?
 
-- | --

**Comment by bedroesb** [comment]
From what I know, yes, this is mandatory to be MIAPPE compliant (regardless the special observation levels that Cyril uses). https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/tree/v1.1#phenotyping

**Comment by PapoutsoglouE** [comment]
> Characteristics[Observation Unit Type] in assay file.

I think this was a change that was proposed when we decided to only allow 1 observation level per assay file (in https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/commit/1d07856cdb5d8bd2d41eece19fce145d1b105a47), and the purpose was to emphasize this. For people using the ISA creator it is not a huge deal because the technology selection ensures that this is the case.  
But I think that our thinking was that this (redundant) column would make it clearer for people who use other methods to generate these files.

If you no longer think this is necessary, I don't see much harm in removing it from the assay file. The unit level is included in the Study file anyway, and it can be present inside the data files as well.

**Comment by bedroesb** [comment]
PR #48
