### ISSUE TITLE
Documentation: test endpoints returning an error due to wrong Trial or Study Id as input

### ISSUE THREAD

**Issue by proccaserra** [elixir-europe/plant-brapi-to-isa#60]
on URGI server, Trial and Study Ids no longer have numerical  values
for example, they should be looking like this dXJuOlVSR0kvc3R1ZHkvQlRIX09yZ2V2YWxfMjAwMl9TZXRBMg==

so documentation should reflect this for the conversion to run(*):
`python brapi_to_isa.py -e https://urgi.versailles.inra.fr/faidare/brapi/v1/ -s dXJuOlVSR0kvc3R1ZHkvQlRIX09yZ2V2YWxfMjAwMl9TZXRBMg==`

(*) I am also running into error when converting the Trial associated with 'POPYOMICS' program
(related to https://github.com/ISA-tools/isa-api/issues/344 as I am trying to reproduce the error'

**Comment by bedroesb** [comment]
Good catch. I already use the new ID's in the CI, but forgot to change the documentation.

**Comment by bedroesb** [comment]
fixed in #59
