### ISSUE TITLE
Error on URGI Trial 

### ISSUE THREAD

**Issue by proccaserra** [elixir-europe/plant-brapi-to-isa#61]
was working from `master`:

python brapi_to_isa.py -e https://urgi.versailles.inra.fr/faidare/brapi/v1/ -t aHR0cDovL2R4LmRvaS5vcmcvMTAuMTE4Ni8xNDcxLTIyMjktMTItMTcz

or 

python brapi_to_isa.py -e https://urgi.versailles.inra.fr/faidare/brapi/v1/ -s dXJuOlVSR0kvc3R1ZHkvUE9QWU9NSUNTLVBPUDItVUs=

2019-10-24 11:00:54,154 [ERROR]: brapi_to_isa.py(<module>:501) >> local variable 'c' referenced before assignment
Traceback (most recent call last):
  File "brapi_to_isa.py", line 499, in <module>
    main(arg=SERVER)
  File "brapi_to_isa.py", line 404, in main
    source = Source(name=germ['germplasmName'], characteristics=converter.create_germplasm_chars(germ))
  File "/Users/philippe/Documents/git/elixir-europe/plant-brapi-to-isa/brapi_to_isa_converter.py", line 104, in create_germplasm_chars
    returned_characteristics.append(c)
UnboundLocalError: local variable 'c' referenced before assignment
(brapi2isavenv) ecsgadminsMBP3:plant-brapi-to-isa philippe$ python brapi_to_isa.py -e https://urgi.versailles.inra.fr/faidare/brapi/v1/ -t aHR0cDovL2R4LmRvaS5vcmcvMTAuMTE4Ni8xNDcxLTIyMjktMTItMTcz

fix:
`        if att_test(all_germplasm_attributes, 'taxonIds'):
            taxonId = ''
            for taxonid in all_germplasm_attributes['taxonIds']:
                if taxonid['sourceName'] in ['NCBITaxon', 'ncbiTaxon']:

                    c = self.organism_characteristic(
                        all_germplasm_attributes, taxonid['taxonId'])
                    returned_characteristics.append(c)
            
        else:
            c = self.organism_characteristic(all_germplasm_attributes, "")
            returned_characteristics.append(c)

`

**Comment by proccaserra** [comment]
@bedroesb it seems this is actually fixed in the `dev` branch. I was working from `master`.

**Comment by bedroesb** [comment]
fixed in #59

**Comment by bedroesb** [comment]
@proccaserra I merged to the master, so normally the examples should work now
