### ISSUE TITLE
'nucleic acid sequencing' instead of 'Phenotyping' as protocol type

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/plant-brapi-to-isa#62]
Because `Phenotyping` is not a supported protocol in ISA-tools, we are forced to use `nucleic acid sequencing` as protocol_type to have an assay name column in the assay file. This is not following the MIAPPE standard, so it is needed to manually change this in the investigation file to `Phenotyping`.

#https://github.com/ISA-tools/isa-api/issues/345

**Comment by proccaserra** [comment]
@bedroesb: This is trivial to fix in `isa-api`, i am about to push a change shortly. Note that we'll be using lower case `phenotyping`.
